name: pullapprove
description: PullApprove CLI utilities
branding:
  icon: user-check
  color: white
inputs:
  cmd:
    description: 'Command arguments for the pullapprove CLI'
    required: true
  github_token:
    required: true
runs:
  using: composite
  steps:
  - run: pip3 install $GITHUB_ACTION_PATH
    shell: bash
  - run: pullapprove ${{ inputs.cmd }}
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
