name: pullapprove
description: PullApprove CLI utilities
branding:
  icon: user-check
  color: white
inputs:
  cmd:
    description: 'Command arguments for the pullapprove CLI'
    required: true
  github_token:
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.cmd }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
