#!/bin/sh -ex
.venv/bin/mypy pullapprove \
    --ignore-missing-imports \
    --warn-unreachable \
    --disallow-untyped-defs \
    --disallow-incomplete-defs \
    --exclude _vendor \
    --no-incremental \
    --html-report ./.reports/mypy \
    --txt-report ./.reports/mypy
