#!/bin/sh -e
VERSION="$1"

if [ -z "$VERSION" ]
then
    echo "You need to specify a version (ex. '1.0.0')"
    exit 1
fi

echo "Updating pyproject.toml versions"
sed -E -i "" "s/version = \"[0-9]+\.[0-9]+\.[0-9]+\"/version = \"$VERSION\"/g" pyproject.toml
git add pyproject.toml

echo "Updating version in Dockerfile"
sed -E -i "" "s/pullapprove==[0-9]+\.[0-9]+\.[0-9]+/pullapprove==$VERSION/g" Dockerfile
git add Dockerfile

echo "Updating license change date"
CHANGEDATE=$(date -v +3y "+%Y-%m-%d")
sed -E -i "" "s/Change Date:          .*/Change Date:          $CHANGEDATE/g" LICENSE
git add LICENSE

git commit -m "Version $VERSION"
git tag -a "v$VERSION" -m "v$VERSION"

echo "Publishing to pypi"
poetry build
poetry publish

echo "Pushing commits and tag"
git push
git push origin "v$VERSION"

echo "Moving v3 tag for GitHub Actions"
git tag -a v3 -m v3 -f
git push --force origin v3
