name: nextrelease
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [labeled, unlabeled, edited, synchronize]

jobs:
  sync:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' && github.head_ref == 'nextrelease' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # all branches and tags
    - uses: dropseed/nextrelease@v1
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.DROPSEED_PYPI_TOKEN }}
      with:
        prepare_cmd: |
          sed -i -e "s/version = \"[^\"]*\"$/version = \"$VERSION\"/g" pyproject.toml
          sed -i -e "s/pullapprove==.*/pullapprove==$VERSION/g" Dockerfile
          sed -i -e "s/Change Date:          .*/Change Date:          $(date -v +3y '+%Y-%m-%d')/g" LICENSE
        publish_cmd: |
          pip3 install -U pip poetry && poetry publish --build --no-interaction
          git tag -a v$VERSION_MAJOR -m v$VERSION_MAJOR -f && git push origin v$VERSION_MAJOR -f
        github_token: ${{ secrets.GITHUB_TOKEN }}
