name: nextrelease
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [labeled, unlabeled, edited, synchronize]

jobs:
  sync:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' && github.head_ref == 'nextrelease' }}
    runs-on: ubuntu-latest
    steps:
    - uses: dropseed/nextrelease@v2
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.DROPSEED_PYPI_TOKEN }}
      with:
        prepare_cmd: |
          sed -i -e "s/version = \"[^\"]*\"$/version = \"$VERSION\"/g" pyproject.toml
          export CHANGEDATE=$(date -d "+3 years" "+%Y-%m-%d")
          sed -i -e "s/Change Date:          .*/Change Date:          $CHANGEDATE/g" LICENSE
        publish_cmd: |
          pip3 install -U pip poetry && poetry publish --build --no-interaction
          git tag -a v$VERSION_MAJOR -m v$VERSION_MAJOR -f && git push origin v$VERSION_MAJOR -f
        github_token: ${{ secrets.GITHUB_TOKEN }}
